on:
  push:
    # tags:
    #   - 'v*'
    branch:
      - 'githubActions'

name: Create Release

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      ARCHIVE_NAME: ${{ github.event.repository.name }}-${{ github.event.release.tag_name }}
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v2
    - name: Make Release Folder
      run: mkdir "$ARCHIVE_NAME" && cp *.ahk *.md "$ARCHIVE_NAME"
    - name: Archive Release TAR.GZ
      run: tar -czf "$ARCHIVE_NAME".tar.gz "$ARCHIVE_NAME"
    - name: DEBUG
      run: ls -al && cd "$ARCHIVE_NAME" && ls -al
    - name: Archive Release ZIP
      uses: thedoctor0/zip-release@main
      with:
        filename: "$ARCHIVE_NAME.zip"
        type: "zip"
        path: "$ARCHIVE_NAME"
    - name: Upload Release
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        artifacts: "$ARCHIVE_NAME.zip,$ARCHIVE_NAME.tar.gz"
        draft: true
        tag: "TEST"
        token: ${{ secrets.GITHUB_TOKEN }}